/**
 * Error Codes
 * Categorized error codes for client-side handling
 */

export enum ErrorCode {
    // Authentication errors (AUTH_)
    AUTH_REQUIRED = 'AUTH_REQUIRED',
    AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
    AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
    AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
    AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
    AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
    AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
    AUTH_PASSWORD_MISMATCH = 'AUTH_PASSWORD_MISMATCH',
    AUTH_WEAK_PASSWORD = 'AUTH_WEAK_PASSWORD',

    // Authorization errors (AUTHZ_)
    AUTHZ_FORBIDDEN = 'AUTHZ_FORBIDDEN',
    AUTHZ_INSUFFICIENT_PERMISSIONS = 'AUTHZ_INSUFFICIENT_PERMISSIONS',
    AUTHZ_ROLE_REQUIRED = 'AUTHZ_ROLE_REQUIRED',

    // Validation errors (VAL_)
    VAL_INVALID_INPUT = 'VAL_INVALID_INPUT',
    VAL_MISSING_FIELD = 'VAL_MISSING_FIELD',
    VAL_INVALID_FORMAT = 'VAL_INVALID_FORMAT',
    VAL_INVALID_EMAIL = 'VAL_INVALID_EMAIL',
    VAL_INVALID_PHONE = 'VAL_INVALID_PHONE',
    VAL_INVALID_ID = 'VAL_INVALID_ID',

    // Business logic errors (BIZ_)
    BIZ_NOT_FOUND = 'BIZ_NOT_FOUND',
    BIZ_ALREADY_EXISTS = 'BIZ_ALREADY_EXISTS',
    BIZ_CONFLICT = 'BIZ_CONFLICT',
    BIZ_INVALID_STATE = 'BIZ_INVALID_STATE',
    BIZ_LIMIT_EXCEEDED = 'BIZ_LIMIT_EXCEEDED',
    BIZ_OPERATION_FAILED = 'BIZ_OPERATION_FAILED',

    // Resource errors (RES_)
    RES_USER_NOT_FOUND = 'RES_USER_NOT_FOUND',
    RES_COMPANY_NOT_FOUND = 'RES_COMPANY_NOT_FOUND',
    RES_ORDER_NOT_FOUND = 'RES_ORDER_NOT_FOUND',
    RES_SHIPMENT_NOT_FOUND = 'RES_SHIPMENT_NOT_FOUND',
    RES_WAREHOUSE_NOT_FOUND = 'RES_WAREHOUSE_NOT_FOUND',
    RES_ZONE_NOT_FOUND = 'RES_ZONE_NOT_FOUND',
    RES_RATECARD_NOT_FOUND = 'RES_RATECARD_NOT_FOUND',

    // External service errors (EXT_)
    EXT_SERVICE_UNAVAILABLE = 'EXT_SERVICE_UNAVAILABLE',
    EXT_COURIER_FAILURE = 'EXT_COURIER_FAILURE',
    EXT_PAYMENT_FAILURE = 'EXT_PAYMENT_FAILURE',
    EXT_KYC_VERIFICATION_FAILED = 'EXT_KYC_VERIFICATION_FAILED',
    EXT_EMAIL_SEND_FAILED = 'EXT_EMAIL_SEND_FAILED',
    EXT_SMS_SEND_FAILED = 'EXT_SMS_SEND_FAILED',

    // Rate limiting errors (RATE_)
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
    RATE_TOO_MANY_REQUESTS = 'RATE_TOO_MANY_REQUESTS',

    // System errors (SYS_)
    SYS_DATABASE_ERROR = 'SYS_DATABASE_ERROR',
    SYS_INTERNAL_ERROR = 'SYS_INTERNAL_ERROR',
    SYS_MAINTENANCE = 'SYS_MAINTENANCE',
    SYS_TIMEOUT = 'SYS_TIMEOUT',
}

/**
 * HTTP status code mapping for error codes
 */
export const errorStatusMap: Record<ErrorCode, number> = {
    // Auth errors (401)
    [ErrorCode.AUTH_REQUIRED]: 401,
    [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
    [ErrorCode.AUTH_TOKEN_EXPIRED]: 401,
    [ErrorCode.AUTH_TOKEN_INVALID]: 401,
    [ErrorCode.AUTH_ACCOUNT_LOCKED]: 401,
    [ErrorCode.AUTH_ACCOUNT_DISABLED]: 401,
    [ErrorCode.AUTH_EMAIL_NOT_VERIFIED]: 401,
    [ErrorCode.AUTH_PASSWORD_MISMATCH]: 400,
    [ErrorCode.AUTH_WEAK_PASSWORD]: 400,

    // Authorization errors (403)
    [ErrorCode.AUTHZ_FORBIDDEN]: 403,
    [ErrorCode.AUTHZ_INSUFFICIENT_PERMISSIONS]: 403,
    [ErrorCode.AUTHZ_ROLE_REQUIRED]: 403,

    // Validation errors (400)
    [ErrorCode.VAL_INVALID_INPUT]: 400,
    [ErrorCode.VAL_MISSING_FIELD]: 400,
    [ErrorCode.VAL_INVALID_FORMAT]: 400,
    [ErrorCode.VAL_INVALID_EMAIL]: 400,
    [ErrorCode.VAL_INVALID_PHONE]: 400,
    [ErrorCode.VAL_INVALID_ID]: 400,

    // Business errors (400/404/409)
    [ErrorCode.BIZ_NOT_FOUND]: 404,
    [ErrorCode.BIZ_ALREADY_EXISTS]: 409,
    [ErrorCode.BIZ_CONFLICT]: 409,
    [ErrorCode.BIZ_INVALID_STATE]: 400,
    [ErrorCode.BIZ_LIMIT_EXCEEDED]: 400,
    [ErrorCode.BIZ_OPERATION_FAILED]: 400,

    // Resource errors (404)
    [ErrorCode.RES_USER_NOT_FOUND]: 404,
    [ErrorCode.RES_COMPANY_NOT_FOUND]: 404,
    [ErrorCode.RES_ORDER_NOT_FOUND]: 404,
    [ErrorCode.RES_SHIPMENT_NOT_FOUND]: 404,
    [ErrorCode.RES_WAREHOUSE_NOT_FOUND]: 404,
    [ErrorCode.RES_ZONE_NOT_FOUND]: 404,
    [ErrorCode.RES_RATECARD_NOT_FOUND]: 404,

    // External service errors (502/503)
    [ErrorCode.EXT_SERVICE_UNAVAILABLE]: 503,
    [ErrorCode.EXT_COURIER_FAILURE]: 502,
    [ErrorCode.EXT_PAYMENT_FAILURE]: 502,
    [ErrorCode.EXT_KYC_VERIFICATION_FAILED]: 502,
    [ErrorCode.EXT_EMAIL_SEND_FAILED]: 502,
    [ErrorCode.EXT_SMS_SEND_FAILED]: 502,

    // Rate limiting errors (429)
    [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
    [ErrorCode.RATE_TOO_MANY_REQUESTS]: 429,

    // System errors (500/503)
    [ErrorCode.SYS_DATABASE_ERROR]: 500,
    [ErrorCode.SYS_INTERNAL_ERROR]: 500,
    [ErrorCode.SYS_MAINTENANCE]: 503,
    [ErrorCode.SYS_TIMEOUT]: 504,
};
