/**
 * Error Codes
 * Categorized error codes for client-side handling
 */

export enum ErrorCode {
    // Authentication errors (AUTH_)
    AUTH_REQUIRED = 'AUTH_REQUIRED',
    AUTH_SESSION_REQUIRED = 'AUTH_SESSION_REQUIRED',
    AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
    AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
    AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
    AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
    AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
    AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
    AUTH_PASSWORD_MISMATCH = 'AUTH_PASSWORD_MISMATCH',
    AUTH_WEAK_PASSWORD = 'AUTH_WEAK_PASSWORD',
    AUTH_OAUTH_FAILED = 'AUTH_OAUTH_FAILED',
    AUTH_OAUTH_INVALID_PROFILE = 'AUTH_OAUTH_INVALID_PROFILE',
    AUTH_INVALID_PASSWORD = 'AUTH_INVALID_PASSWORD',
    AUTH_VERIFICATION_FAILED = 'AUTH_VERIFICATION_FAILED',
    AUTH_KYC_NOT_VERIFIED = 'AUTH_KYC_NOT_VERIFIED',

    // Authorization errors (AUTHZ_)
    AUTHZ_FORBIDDEN = 'AUTHZ_FORBIDDEN',
    AUTHZ_INSUFFICIENT_PERMISSIONS = 'AUTHZ_INSUFFICIENT_PERMISSIONS',
    AUTHZ_ROLE_REQUIRED = 'AUTHZ_ROLE_REQUIRED',

    // Pricing errors
    PRC_STRICT_PRICING_VIOLATION = 'PRC_STRICT_PRICING_VIOLATION',

    // Validation errors (VAL_)
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    VAL_INVALID_INPUT = 'VAL_INVALID_INPUT',
    VAL_MISSING_FIELD = 'VAL_MISSING_FIELD',
    VAL_INVALID_FORMAT = 'VAL_INVALID_FORMAT',
    VAL_INVALID_EMAIL = 'VAL_INVALID_EMAIL',
    VAL_INVALID_PHONE = 'VAL_INVALID_PHONE',
    VAL_INVALID_ID = 'VAL_INVALID_ID',

    // Address validation errors
    VAL_ADDRESS_INVALID = 'VAL_ADDRESS_INVALID',
    VAL_PINCODE_INVALID = 'VAL_PINCODE_INVALID',
    VAL_PINCODE_NOT_SERVICEABLE = 'VAL_PINCODE_NOT_SERVICEABLE',

    // Business logic errors (BIZ_)
    BIZ_NOT_FOUND = 'BIZ_NOT_FOUND',
    BIZ_ALREADY_EXISTS = 'BIZ_ALREADY_EXISTS',
    BIZ_CONFLICT = 'BIZ_CONFLICT',
    BIZ_INVALID_STATE = 'BIZ_INVALID_STATE',
    BIZ_LIMIT_EXCEEDED = 'BIZ_LIMIT_EXCEEDED',
    BIZ_OPERATION_FAILED = 'BIZ_OPERATION_FAILED',
    BIZ_SHIPMENT_EXISTS = 'BIZ_SHIPMENT_EXISTS',
    BIZ_TRACKING_NUMBER_GENERATION_FAILED = 'BIZ_TRACKING_NUMBER_GENERATION_FAILED',
    BIZ_ORDER_NUMBER_GENERATION_FAILED = 'BIZ_ORDER_NUMBER_GENERATION_FAILED',
    BIZ_CONCURRENT_MODIFICATION = 'BIZ_CONCURRENT_MODIFICATION',
    BIZ_SETUP_FAILED = 'BIZ_SETUP_FAILED',
    BIZ_SETUP_REQUIRED = 'BIZ_SETUP_REQUIRED',
    BIZ_RULE_VIOLATION = 'BIZ_RULE_VIOLATION',
    BIZ_DISCREPANCY_NOT_FOUND = 'BIZ_DISCREPANCY_NOT_FOUND',
    BIZ_DISCREPANCY_ALREADY_RESOLVED = 'BIZ_DISCREPANCY_ALREADY_RESOLVED',

    // Financial errors (BIZ_)
    BIZ_INSUFFICIENT_BALANCE = 'BIZ_INSUFFICIENT_BALANCE',
    BIZ_WALLET_TRANSACTION_FAILED = 'BIZ_WALLET_TRANSACTION_FAILED',
    BIZ_COD_REMITTANCE_FAILED = 'BIZ_COD_REMITTANCE_FAILED',
    BIZ_PAYOUT_FAILED = 'BIZ_PAYOUT_FAILED',
    BIZ_RISK_CHECK_FAILED = 'BIZ_RISK_CHECK_FAILED',

    // Concurrency errors (BIZ_)
    BIZ_VERSION_CONFLICT = 'BIZ_VERSION_CONFLICT',
    BIZ_OPTIMISTIC_LOCK_FAILURE = 'BIZ_OPTIMISTIC_LOCK_FAILURE',

    // Resource errors (RES_)
    RES_RESOURCE_NOT_FOUND = 'RES_RESOURCE_NOT_FOUND',
    RES_USER_NOT_FOUND = 'RES_USER_NOT_FOUND',
    RES_COMPANY_NOT_FOUND = 'RES_COMPANY_NOT_FOUND',
    RES_ORDER_NOT_FOUND = 'RES_ORDER_NOT_FOUND',
    RES_SHIPMENT_NOT_FOUND = 'RES_SHIPMENT_NOT_FOUND',
    RES_WAREHOUSE_NOT_FOUND = 'RES_WAREHOUSE_NOT_FOUND',
    RES_ZONE_NOT_FOUND = 'RES_ZONE_NOT_FOUND',
    RES_RATECARD_NOT_FOUND = 'RES_RATECARD_NOT_FOUND',
    RES_REMITTANCE_NOT_FOUND = 'RES_REMITTANCE_NOT_FOUND',
    RES_INTEGRATION_NOT_FOUND = 'RES_INTEGRATION_NOT_FOUND',
    RES_NOT_FOUND = 'RES_NOT_FOUND',
    RES_KYC_NOT_FOUND = 'RES_KYC_NOT_FOUND',
    RES_KYC_ALREADY_EXISTS = 'RES_KYC_ALREADY_EXISTS',
    RES_KYC_CONFLICT = 'RES_KYC_CONFLICT',
    RES_KYC_INVALID_STATE = 'RES_KYC_INVALID_STATE',
    RES_KYC_LIMIT_EXCEEDED = 'RES_KYC_LIMIT_EXCEEDED',
    RES_KYC_OPERATION_FAILED = 'RES_KYC_OPERATION_FAILED',
    RES_KYC_CONCURRENT_MODIFICATION = 'RES_KYC_CONCURRENT_MODIFICATION',
    RES_KYC_SETUP_FAILED = 'RES_KYC_SETUP_FAILED',
    RES_KYC_VERSION_CONFLICT = 'RES_KYC_VERSION_CONFLICT',
    RES_KYC_OPTIMISTIC_LOCK_FAILURE = 'RES_KYC_OPTIMISTIC_LOCK_FAILURE',


    // External service errors (EXT_)
    EXT_SERVICE_UNAVAILABLE = 'EXT_SERVICE_UNAVAILABLE',
    EXT_SERVICE_ERROR = 'EXT_SERVICE_ERROR',
    EXT_COURIER_FAILURE = 'EXT_COURIER_FAILURE',
    EXT_PAYMENT_FAILURE = 'EXT_PAYMENT_FAILURE',
    EXT_KYC_VERIFICATION_FAILED = 'EXT_KYC_VERIFICATION_FAILED',
    EXT_EMAIL_SEND_FAILED = 'EXT_EMAIL_SEND_FAILED',
    EXT_SMS_SEND_FAILED = 'EXT_SMS_SEND_FAILED',
    EXT_PAYMENT_FAILED = 'EXT_PAYMENT_FAILED',

    // Rate limiting errors (RATE_)
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
    RATE_TOO_MANY_REQUESTS = 'RATE_TOO_MANY_REQUESTS',

    // System errors (SYS_)
    SYS_DATABASE_ERROR = 'SYS_DATABASE_ERROR',
    SYS_DB_OPERATION_FAILED = 'SYS_DB_OPERATION_FAILED',
    SYS_INTERNAL_ERROR = 'SYS_INTERNAL_ERROR',
    SYS_MAINTENANCE = 'SYS_MAINTENANCE',
    SYS_TIMEOUT = 'SYS_TIMEOUT',
}

/**
 * HTTP status code mapping for error codes
 */
export const errorStatusMap: Record<ErrorCode, number> = {
    // Auth errors (401)
    [ErrorCode.AUTH_REQUIRED]: 401,
    [ErrorCode.AUTH_SESSION_REQUIRED]: 401,
    [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
    [ErrorCode.AUTH_TOKEN_EXPIRED]: 401,
    [ErrorCode.AUTH_TOKEN_INVALID]: 401,
    [ErrorCode.AUTH_ACCOUNT_LOCKED]: 401,
    [ErrorCode.AUTH_ACCOUNT_DISABLED]: 401,
    [ErrorCode.AUTH_EMAIL_NOT_VERIFIED]: 401,
    [ErrorCode.AUTH_PASSWORD_MISMATCH]: 400,
    [ErrorCode.AUTH_WEAK_PASSWORD]: 400,
    [ErrorCode.AUTH_OAUTH_FAILED]: 401,
    [ErrorCode.AUTH_OAUTH_INVALID_PROFILE]: 400,
    [ErrorCode.AUTH_INVALID_PASSWORD]: 401,
    [ErrorCode.AUTH_VERIFICATION_FAILED]: 401,
    [ErrorCode.AUTH_KYC_NOT_VERIFIED]: 403,

    // Authorization errors (403)
    [ErrorCode.AUTHZ_FORBIDDEN]: 403,
    [ErrorCode.AUTHZ_INSUFFICIENT_PERMISSIONS]: 403,
    [ErrorCode.AUTHZ_ROLE_REQUIRED]: 403,

    // Pricing errors
    [ErrorCode.PRC_STRICT_PRICING_VIOLATION]: 400,

    // Validation errors (400)
    [ErrorCode.VALIDATION_ERROR]: 400,
    [ErrorCode.VAL_INVALID_INPUT]: 400,
    [ErrorCode.VAL_MISSING_FIELD]: 400,
    [ErrorCode.VAL_INVALID_FORMAT]: 400,
    [ErrorCode.VAL_INVALID_EMAIL]: 400,
    [ErrorCode.VAL_INVALID_PHONE]: 400,
    [ErrorCode.VAL_INVALID_ID]: 400,

    // Address validation errors (400)
    [ErrorCode.VAL_ADDRESS_INVALID]: 400,
    [ErrorCode.VAL_PINCODE_INVALID]: 400,
    [ErrorCode.VAL_PINCODE_NOT_SERVICEABLE]: 400,

    // Business errors (400/404/409)
    [ErrorCode.BIZ_NOT_FOUND]: 404,
    [ErrorCode.BIZ_ALREADY_EXISTS]: 409,
    [ErrorCode.BIZ_CONFLICT]: 409,
    [ErrorCode.BIZ_INVALID_STATE]: 400,
    [ErrorCode.BIZ_LIMIT_EXCEEDED]: 429,
    [ErrorCode.BIZ_OPERATION_FAILED]: 500,
    [ErrorCode.BIZ_SHIPMENT_EXISTS]: 409,
    [ErrorCode.BIZ_TRACKING_NUMBER_GENERATION_FAILED]: 500,
    [ErrorCode.BIZ_ORDER_NUMBER_GENERATION_FAILED]: 500,
    [ErrorCode.BIZ_CONCURRENT_MODIFICATION]: 409,
    [ErrorCode.BIZ_SETUP_FAILED]: 500,
    [ErrorCode.BIZ_SETUP_REQUIRED]: 403, // Setup incomplete - forbidden until onboarding complete
    [ErrorCode.BIZ_INSUFFICIENT_BALANCE]: 400,
    [ErrorCode.BIZ_WALLET_TRANSACTION_FAILED]: 500,
    [ErrorCode.BIZ_COD_REMITTANCE_FAILED]: 500,
    [ErrorCode.BIZ_PAYOUT_FAILED]: 500,
    [ErrorCode.BIZ_RISK_CHECK_FAILED]: 400,
    [ErrorCode.BIZ_RULE_VIOLATION]: 400,
    [ErrorCode.BIZ_DISCREPANCY_NOT_FOUND]: 404,
    [ErrorCode.BIZ_DISCREPANCY_ALREADY_RESOLVED]: 400,

    // Concurrency errors (409)
    [ErrorCode.BIZ_VERSION_CONFLICT]: 409,
    [ErrorCode.BIZ_OPTIMISTIC_LOCK_FAILURE]: 409,

    // Resource errors (404)
    [ErrorCode.RES_USER_NOT_FOUND]: 404,
    [ErrorCode.RES_COMPANY_NOT_FOUND]: 404,
    [ErrorCode.RES_ORDER_NOT_FOUND]: 404,
    [ErrorCode.RES_SHIPMENT_NOT_FOUND]: 404,
    [ErrorCode.RES_WAREHOUSE_NOT_FOUND]: 404,
    [ErrorCode.RES_ZONE_NOT_FOUND]: 404,
    [ErrorCode.RES_RATECARD_NOT_FOUND]: 404,
    [ErrorCode.RES_REMITTANCE_NOT_FOUND]: 404,
    [ErrorCode.RES_INTEGRATION_NOT_FOUND]: 404,
    [ErrorCode.RES_NOT_FOUND]: 404,
    [ErrorCode.RES_RESOURCE_NOT_FOUND]: 404,
    [ErrorCode.RES_KYC_NOT_FOUND]: 404,
    [ErrorCode.RES_KYC_ALREADY_EXISTS]: 409,
    [ErrorCode.RES_KYC_CONFLICT]: 409,
    [ErrorCode.RES_KYC_INVALID_STATE]: 400,
    [ErrorCode.RES_KYC_LIMIT_EXCEEDED]: 429,
    [ErrorCode.RES_KYC_OPERATION_FAILED]: 500,
    [ErrorCode.RES_KYC_CONCURRENT_MODIFICATION]: 409,
    [ErrorCode.RES_KYC_SETUP_FAILED]: 500,
    [ErrorCode.RES_KYC_VERSION_CONFLICT]: 409,
    [ErrorCode.RES_KYC_OPTIMISTIC_LOCK_FAILURE]: 409,

    // External service errors (502/503)
    [ErrorCode.EXT_SERVICE_UNAVAILABLE]: 503,
    [ErrorCode.EXT_SERVICE_ERROR]: 502,
    [ErrorCode.EXT_COURIER_FAILURE]: 502,
    [ErrorCode.EXT_PAYMENT_FAILURE]: 502,
    [ErrorCode.EXT_KYC_VERIFICATION_FAILED]: 502,
    [ErrorCode.EXT_EMAIL_SEND_FAILED]: 502,
    [ErrorCode.EXT_SMS_SEND_FAILED]: 502,
    [ErrorCode.EXT_PAYMENT_FAILED]: 502,

    // Rate limiting errors (429)
    [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
    [ErrorCode.RATE_TOO_MANY_REQUESTS]: 429,

    // System errors (500/503)
    [ErrorCode.SYS_DATABASE_ERROR]: 500,
    [ErrorCode.SYS_DB_OPERATION_FAILED]: 500,
    [ErrorCode.SYS_INTERNAL_ERROR]: 500,
    [ErrorCode.SYS_MAINTENANCE]: 503,
    [ErrorCode.SYS_TIMEOUT]: 504,
};
